FROM docker.io/golang:1.22-bookworm

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -yq flex bison bc libssl-dev libelf-dev cpio dosfstools mtools syslinux \
 && rm -rf /var/lib/apt/lists/*